# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Don't Touch My Mushroom
email: info@dont-tou.ch
description: > # this means to ignore newlines until "baseurl:"
  "Don't Touch My Mushroom" is an improvisional theatre company that
  grows & performs in Zurich, Switzerland. Despite not
  having a single native speaker, we proudly perform
  in English with a wide variety accents and oddities.
baseurl: "/" # the subpath of your site, e.g. /blog
# Overridden in default.nix
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
future: true
# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
  - docs
  - nix
  - "*.nix"
